// Command gen-top-ports regenerates the tail of the Top1000 port list
// from IANA's registry.
//
// The top100 prefix is hand-curated in internal/portscan/top.go (nmap
// frequency ordering) and preserved verbatim by this generator. The
// remaining 900 slots are filled with IANA-assigned TCP ports in
// numeric order, skipping any already in top100.
//
// Usage:
//
//	gen-top-ports -in data/iana-service-names-port-numbers.csv \
//	              -out internal/portscan/top.go
//
// Rationale: nmap-services has richer frequency data but ships under
// a copyleft license incompatible with scry's MIT. See scry-plan.md
// §10 #23. The resulting top1000 is less accurate than nmap's for
// ports 101–1000 but is license-clean and reproducible.
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

// top100 must stay in exact sync with the literal in
// internal/portscan/top.go. Kept here as a copy so the generator is
// self-contained and can emit the full file from scratch.
var top100 = []uint16{
	80, 23, 443, 21, 22, 25, 3389, 110, 445, 139,
	143, 53, 135, 3306, 8080, 1723, 111, 995, 993, 5900,
	1025, 587, 8888, 199, 1720, 465, 548, 113, 81, 6001,
	10000, 514, 5060, 179, 1026, 2000, 8443, 8000, 32768, 554,
	26, 1433, 49152, 2001, 515, 8008, 49154, 1027, 5666, 646,
	5000, 5631, 631, 49153, 8081, 2049, 88, 79, 5800, 106,
	2121, 1110, 49155, 6000, 513, 990, 5357, 427, 49156, 543,
	544, 5101, 144, 7, 389, 8009, 3128, 444, 9999, 5009,
	7070, 5190, 3000, 5432, 1900, 3986, 13, 1029, 9, 5051,
	6646, 49157, 1028, 873, 1755, 2717, 4899, 9100, 119, 37,
}

func main() {
	var (
		inPath  = flag.String("in", "data/iana-service-names-port-numbers.csv", "IANA registry CSV")
		outPath = flag.String("out", "internal/portscan/top.go", "generated Go file")
	)
	flag.Parse()

	assigned, err := readIANATCPPorts(*inPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-top-ports:", err)
		os.Exit(1)
	}
	top1000 := buildTop1000(top100, assigned)
	if err := writeGo(*outPath, top100, top1000); err != nil {
		fmt.Fprintln(os.Stderr, "gen-top-ports:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-top-ports: wrote %d entries to %s\n", len(top1000), *outPath)
}

func readIANATCPPorts(path string) (map[uint16]struct{}, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.FieldsPerRecord = -1

	header, err := r.Read()
	if err != nil {
		return nil, err
	}
	col := make(map[string]int, len(header))
	for i, h := range header {
		col[strings.TrimSpace(h)] = i
	}
	svcIdx := col["Service Name"]
	portIdx := col["Port Number"]
	protoIdx := col["Transport Protocol"]

	out := make(map[uint16]struct{}, 4096)
	for {
		row, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if row[protoIdx] != "tcp" {
			continue
		}
		if strings.TrimSpace(row[svcIdx]) == "" {
			continue
		}
		portStr := strings.TrimSpace(row[portIdx])
		if portStr == "" || strings.Contains(portStr, "-") {
			continue
		}
		n, err := strconv.Atoi(portStr)
		if err != nil || n < 1 || n > 65535 {
			continue
		}
		out[uint16(n)] = struct{}{}
	}
	return out, nil
}

// buildTop1000 returns top100 followed by up to 900 ports from
// `assigned`, in numeric order, skipping ports already in top100.
// If the registry has fewer than 900 unused assigned ports (unlikely)
// the slice is shorter than 1000.
func buildTop1000(top100 []uint16, assigned map[uint16]struct{}) []uint16 {
	seen := make(map[uint16]struct{}, len(top100))
	for _, p := range top100 {
		seen[p] = struct{}{}
	}
	tail := make([]uint16, 0, len(assigned))
	for p := range assigned {
		if _, dup := seen[p]; dup {
			continue
		}
		tail = append(tail, p)
	}
	sort.Slice(tail, func(i, j int) bool { return tail[i] < tail[j] })
	if len(tail) > 900 {
		tail = tail[:900]
	}
	out := make([]uint16, 0, 1000)
	out = append(out, top100...)
	out = append(out, tail...)
	return out
}

func writeGo(path string, top100, top1000 []uint16) error {
	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by cmd/gen-top-ports; DO NOT EDIT.")
	fmt.Fprintln(&b, "// top100 is hand-maintained (nmap frequency order); the remaining 900")
	fmt.Fprintln(&b, "// slots are IANA-assigned TCP ports in numeric order.")
	fmt.Fprintln(&b, "// Source: data/iana-service-names-port-numbers.csv (IANA, public domain).")
	fmt.Fprintf(&b, "// Regenerated %s via `make regen-data`.\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintln(&b, "//")
	fmt.Fprintln(&b, "// See scry-plan.md §10 #23 for the data-source decision.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package portscan")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// top100 is the 100 most commonly-open TCP ports, in nmap frequency order.")
	fmt.Fprintln(&b, "// Hand-curated; update by editing cmd/gen-top-ports/main.go and re-running")
	fmt.Fprintln(&b, "// `make regen-data`.")
	fmt.Fprintln(&b, "var top100 = []uint16{")
	writeSlice(&b, top100, 10)
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "// top1000 prepends top100 and fills the remaining 900 slots with\n")
	fmt.Fprintln(&b, "// IANA-assigned TCP ports in numeric order, skipping duplicates.")
	fmt.Fprintln(&b, "var top1000 = []uint16{")
	writeSlice(&b, top1000, 10)
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Top100 returns a copy of the 100 most common TCP ports.")
	fmt.Fprintln(&b, "func Top100() []uint16 {")
	fmt.Fprintln(&b, "\tout := make([]uint16, len(top100))")
	fmt.Fprintln(&b, "\tcopy(out, top100)")
	fmt.Fprintln(&b, "\treturn out")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Top1000 returns a copy of the top 1000 TCP ports.")
	fmt.Fprintln(&b, "func Top1000() []uint16 {")
	fmt.Fprintln(&b, "\tout := make([]uint16, len(top1000))")
	fmt.Fprintln(&b, "\tcopy(out, top1000)")
	fmt.Fprintln(&b, "\treturn out")
	fmt.Fprintln(&b, "}")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	return os.WriteFile(path, src, 0o644)
}

// writeSlice writes ports in groups of `perLine` with a trailing comma.
func writeSlice(b *strings.Builder, ports []uint16, perLine int) {
	for i, p := range ports {
		if i%perLine == 0 {
			b.WriteString("\t")
		}
		fmt.Fprintf(b, "%d, ", p)
		if i%perLine == perLine-1 {
			b.WriteString("\n")
		}
	}
	if len(ports)%perLine != 0 {
		b.WriteString("\n")
	}
}
