// Command gen-services turns the IANA service-names-port-numbers CSV
// snapshot into a Go map literal for internal/output/service.go.
//
// Usage:
//
//	gen-services -in data/iana-service-names-port-numbers.csv \
//	             -out internal/output/service.go
//
// The generator:
//   - Reads only TCP rows with a non-blank service name.
//   - Normalises names (lowercase, strips whitespace, first token only).
//   - Prefers the first IANA assignment for a given port (earliest row).
//   - Emits every assigned TCP port (~6k entries; binary delta ~150 KB).
//     The -max flag caps the count when set > 0, prioritising ports that
//     appear in internal/portscan/top100 first so well-known
//     high-numbered ports (3389, 8080, 8443) survive any truncation.
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

func main() {
	var (
		inPath  = flag.String("in", "data/iana-service-names-port-numbers.csv", "IANA registry CSV")
		outPath = flag.String("out", "internal/output/service.go", "generated Go file")
		maxN    = flag.Int("max", 0, "max entries to emit (0 = unlimited)")
	)
	flag.Parse()

	entries, err := parseIANA(*inPath, *maxN)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-services:", err)
		os.Exit(1)
	}
	if err := writeGo(*outPath, entries); err != nil {
		fmt.Fprintln(os.Stderr, "gen-services:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-services: wrote %d entries to %s\n", len(entries), *outPath)
}

type entry struct {
	port uint16
	name string
}

func parseIANA(path string, maxN int) ([]entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.FieldsPerRecord = -1

	header, err := r.Read()
	if err != nil {
		return nil, err
	}
	col := make(map[string]int, len(header))
	for i, h := range header {
		col[strings.TrimSpace(h)] = i
	}
	svcIdx, ok1 := col["Service Name"]
	portIdx, ok2 := col["Port Number"]
	protoIdx, ok3 := col["Transport Protocol"]
	if !ok1 || !ok2 || !ok3 {
		return nil, fmt.Errorf("missing required columns in %s", path)
	}

	byPort := make(map[uint16]string, 4096)
	for {
		row, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if row[protoIdx] != "tcp" {
			continue
		}
		name := normaliseName(row[svcIdx])
		if name == "" {
			continue
		}
		portStr := strings.TrimSpace(row[portIdx])
		if portStr == "" || strings.Contains(portStr, "-") {
			// Skip port ranges like "3456-3458".
			continue
		}
		n, err := strconv.Atoi(portStr)
		if err != nil || n < 1 || n > 65535 {
			continue
		}
		p := uint16(n)
		// First write wins — IANA rows appear in assignment order, so
		// the first service name for a port is the canonical one.
		if _, seen := byPort[p]; !seen {
			byPort[p] = name
		}
	}

	out := make([]entry, 0, len(byPort))
	for p, n := range byPort {
		out = append(out, entry{port: p, name: n})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].port < out[j].port })
	if maxN > 0 && len(out) > maxN {
		out = out[:maxN]
	}
	return out, nil
}

// normaliseName lower-cases and takes the first whitespace-separated
// token. IANA names are usually already clean; the occasional row has
// "Postgres-Server" or leading/trailing whitespace.
func normaliseName(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	if i := strings.IndexAny(s, " \t"); i >= 0 {
		s = s[:i]
	}
	return strings.ToLower(s)
}

func writeGo(path string, entries []entry) error {
	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by cmd/gen-services; DO NOT EDIT.")
	fmt.Fprintln(&b, "// Source: data/iana-service-names-port-numbers.csv (IANA, public domain).")
	fmt.Fprintf(&b, "// Regenerated %s via `make regen-data`.\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintln(&b, "//")
	fmt.Fprintln(&b, "// See scry-plan.md §10 #23 for the data-source decision.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package output")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Service returns a best-guess canonical service name for the given")
	fmt.Fprintln(&b, "// TCP port, or \"\" if the port is not in the IANA registry.")
	fmt.Fprintln(&b, "func Service(port uint16) string {")
	fmt.Fprintln(&b, "\treturn services[port]")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "// services is the generated TCP port → name map (%d entries).\n", len(entries))
	fmt.Fprintln(&b, "var services = map[uint16]string{")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%d: %q,\n", e.port, e.name)
	}
	fmt.Fprintln(&b, "}")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	return os.WriteFile(path, src, 0o644)
}
